// Concept Matrix 3.
// Licensed under the MIT license.

namespace ConceptMatrix.Offsets
{
	using System;

	[Serializable]
	public struct Bones
	{
		public string Root_X { get; set; }
		public string Root_Y { get; set; }
		public string Root_Z { get; set; }
		public string Root_W { get; set; }
		public string Abdomen_X { get; set; }
		public string Abdomen_Y { get; set; }
		public string Abdomen_Z { get; set; }
		public string Abdomen_W { get; set; }
		public string Throw_X { get; set; }
		public string Throw_Y { get; set; }
		public string Throw_Z { get; set; }
		public string Throw_W { get; set; }
		public string Waist_X { get; set; }
		public string Waist_Y { get; set; }
		public string Waist_Z { get; set; }
		public string Waist_W { get; set; }
		public string SpineA_X { get; set; }
		public string SpineA_Y { get; set; }
		public string SpineA_Z { get; set; }
		public string SpineA_W { get; set; }
		public string LegLeft_X { get; set; }
		public string LegLeft_Y { get; set; }
		public string LegLeft_Z { get; set; }
		public string LegLeft_W { get; set; }
		public string LegRight_X { get; set; }
		public string LegRight_Y { get; set; }
		public string LegRight_Z { get; set; }
		public string LegRight_W { get; set; }
		public string HolsterLeft_X { get; set; }
		public string HolsterLeft_Y { get; set; }
		public string HolsterLeft_Z { get; set; }
		public string HolsterLeft_W { get; set; }
		public string HolsterRight_X { get; set; }
		public string HolsterRight_Y { get; set; }
		public string HolsterRight_Z { get; set; }
		public string HolsterRight_W { get; set; }
		public string SheatheLeft_X { get; set; }
		public string SheatheLeft_Y { get; set; }
		public string SheatheLeft_Z { get; set; }
		public string SheatheLeft_W { get; set; }
		public string SheatheRight_X { get; set; }
		public string SheatheRight_Y { get; set; }
		public string SheatheRight_Z { get; set; }
		public string SheatheRight_W { get; set; }
		public string SpineB_X { get; set; }
		public string SpineB_Y { get; set; }
		public string SpineB_Z { get; set; }
		public string SpineB_W { get; set; }
		public string ClothBackALeft_X { get; set; }
		public string ClothBackALeft_Y { get; set; }
		public string ClothBackALeft_Z { get; set; }
		public string ClothBackALeft_W { get; set; }
		public string ClothBackARight_X { get; set; }
		public string ClothBackARight_Y { get; set; }
		public string ClothBackARight_Z { get; set; }
		public string ClothBackARight_W { get; set; }
		public string ClothFrontALeft_X { get; set; }
		public string ClothFrontALeft_Y { get; set; }
		public string ClothFrontALeft_Z { get; set; }
		public string ClothFrontALeft_W { get; set; }
		public string ClothFrontARight_X { get; set; }
		public string ClothFrontARight_Y { get; set; }
		public string ClothFrontARight_Z { get; set; }
		public string ClothFrontARight_W { get; set; }
		public string ClothSideALeft_X { get; set; }
		public string ClothSideALeft_Y { get; set; }
		public string ClothSideALeft_Z { get; set; }
		public string ClothSideALeft_W { get; set; }
		public string ClothSideARight_X { get; set; }
		public string ClothSideARight_Y { get; set; }
		public string ClothSideARight_Z { get; set; }
		public string ClothSideARight_W { get; set; }
		public string KneeLeft_X { get; set; }
		public string KneeLeft_Y { get; set; }
		public string KneeLeft_Z { get; set; }
		public string KneeLeft_W { get; set; }
		public string KneeRight_X { get; set; }
		public string KneeRight_Y { get; set; }
		public string KneeRight_Z { get; set; }
		public string KneeRight_W { get; set; }
		public string BreastLeft_X { get; set; }
		public string BreastLeft_Y { get; set; }
		public string BreastLeft_Z { get; set; }
		public string BreastLeft_W { get; set; }
		public string BreastRight_X { get; set; }
		public string BreastRight_Y { get; set; }
		public string BreastRight_Z { get; set; }
		public string BreastRight_W { get; set; }
		public string SpineC_X { get; set; }
		public string SpineC_Y { get; set; }
		public string SpineC_Z { get; set; }
		public string SpineC_W { get; set; }
		public string ClothBackBLeft_X { get; set; }
		public string ClothBackBLeft_Y { get; set; }
		public string ClothBackBLeft_Z { get; set; }
		public string ClothBackBLeft_W { get; set; }
		public string ClothBackBRight_X { get; set; }
		public string ClothBackBRight_Y { get; set; }
		public string ClothBackBRight_Z { get; set; }
		public string ClothBackBRight_W { get; set; }
		public string ClothFrontBLeft_X { get; set; }
		public string ClothFrontBLeft_Y { get; set; }
		public string ClothFrontBLeft_Z { get; set; }
		public string ClothFrontBLeft_W { get; set; }
		public string ClothFrontBRight_X { get; set; }
		public string ClothFrontBRight_Y { get; set; }
		public string ClothFrontBRight_Z { get; set; }
		public string ClothFrontBRight_W { get; set; }
		public string ClothSideBLeft_X { get; set; }
		public string ClothSideBLeft_Y { get; set; }
		public string ClothSideBLeft_Z { get; set; }
		public string ClothSideBLeft_W { get; set; }
		public string ClothSideBRight_X { get; set; }
		public string ClothSideBRight_Y { get; set; }
		public string ClothSideBRight_Z { get; set; }
		public string ClothSideBRight_W { get; set; }
		public string CalfLeft_X { get; set; }
		public string CalfLeft_Y { get; set; }
		public string CalfLeft_Z { get; set; }
		public string CalfLeft_W { get; set; }
		public string CalfRight_X { get; set; }
		public string CalfRight_Y { get; set; }
		public string CalfRight_Z { get; set; }
		public string CalfRight_W { get; set; }
		public string ScabbardLeft_X { get; set; }
		public string ScabbardLeft_Y { get; set; }
		public string ScabbardLeft_Z { get; set; }
		public string ScabbardLeft_W { get; set; }
		public string ScabbardRight_X { get; set; }
		public string ScabbardRight_Y { get; set; }
		public string ScabbardRight_Z { get; set; }
		public string ScabbardRight_W { get; set; }
		public string Neck_X { get; set; }
		public string Neck_Y { get; set; }
		public string Neck_Z { get; set; }
		public string Neck_W { get; set; }
		public string ClavicleLeft_X { get; set; }
		public string ClavicleLeft_Y { get; set; }
		public string ClavicleLeft_Z { get; set; }
		public string ClavicleLeft_W { get; set; }
		public string ClavicleRight_X { get; set; }
		public string ClavicleRight_Y { get; set; }
		public string ClavicleRight_Z { get; set; }
		public string ClavicleRight_W { get; set; }
		public string ClothBackCLeft_X { get; set; }
		public string ClothBackCLeft_Y { get; set; }
		public string ClothBackCLeft_Z { get; set; }
		public string ClothBackCLeft_W { get; set; }
		public string ClothBackCRight_X { get; set; }
		public string ClothBackCRight_Y { get; set; }
		public string ClothBackCRight_Z { get; set; }
		public string ClothBackCRight_W { get; set; }
		public string ClothFrontCLeft_X { get; set; }
		public string ClothFrontCLeft_Y { get; set; }
		public string ClothFrontCLeft_Z { get; set; }
		public string ClothFrontCLeft_W { get; set; }
		public string ClothFrontCRight_X { get; set; }
		public string ClothFrontCRight_Y { get; set; }
		public string ClothFrontCRight_Z { get; set; }
		public string ClothFrontCRight_W { get; set; }
		public string ClothSideCLeft_X { get; set; }
		public string ClothSideCLeft_Y { get; set; }
		public string ClothSideCLeft_Z { get; set; }
		public string ClothSideCLeft_W { get; set; }
		public string ClothSideCRight_X { get; set; }
		public string ClothSideCRight_Y { get; set; }
		public string ClothSideCRight_Z { get; set; }
		public string ClothSideCRight_W { get; set; }
		public string PoleynLeft_X { get; set; }
		public string PoleynLeft_Y { get; set; }
		public string PoleynLeft_Z { get; set; }
		public string PoleynLeft_W { get; set; }
		public string PoleynRight_X { get; set; }
		public string PoleynRight_Y { get; set; }
		public string PoleynRight_Z { get; set; }
		public string PoleynRight_W { get; set; }
		public string FootLeft_X { get; set; }
		public string FootLeft_Y { get; set; }
		public string FootLeft_Z { get; set; }
		public string FootLeft_W { get; set; }
		public string FootRight_X { get; set; }
		public string FootRight_Y { get; set; }
		public string FootRight_Z { get; set; }
		public string FootRight_W { get; set; }
		public string Head_X { get; set; }
		public string Head_Y { get; set; }
		public string Head_Z { get; set; }
		public string Head_W { get; set; }
		public string ArmLeft_X { get; set; }
		public string ArmLeft_Y { get; set; }
		public string ArmLeft_Z { get; set; }
		public string ArmLeft_W { get; set; }
		public string ArmRight_X { get; set; }
		public string ArmRight_Y { get; set; }
		public string ArmRight_Z { get; set; }
		public string ArmRight_W { get; set; }
		public string PauldronLeft_X { get; set; }
		public string PauldronLeft_Y { get; set; }
		public string PauldronLeft_Z { get; set; }
		public string PauldronLeft_W { get; set; }
		public string PauldronRight_X { get; set; }
		public string PauldronRight_Y { get; set; }
		public string PauldronRight_Z { get; set; }
		public string PauldronRight_W { get; set; }
		public string Unknown00_X { get; set; }
		public string Unknown00_Y { get; set; }
		public string Unknown00_Z { get; set; }
		public string Unknown00_W { get; set; }
		public string ToesLeft_X { get; set; }
		public string ToesLeft_Y { get; set; }
		public string ToesLeft_Z { get; set; }
		public string ToesLeft_W { get; set; }
		public string ToesRight_X { get; set; }
		public string ToesRight_Y { get; set; }
		public string ToesRight_Z { get; set; }
		public string ToesRight_W { get; set; }
		public string HairA_X { get; set; }
		public string HairA_Y { get; set; }
		public string HairA_Z { get; set; }
		public string HairA_W { get; set; }
		public string HairFrontLeft_X { get; set; }
		public string HairFrontLeft_Y { get; set; }
		public string HairFrontLeft_Z { get; set; }
		public string HairFrontLeft_W { get; set; }
		public string HairFrontRight_X { get; set; }
		public string HairFrontRight_Y { get; set; }
		public string HairFrontRight_Z { get; set; }
		public string HairFrontRight_W { get; set; }
		public string EarLeft_X { get; set; }
		public string EarLeft_Y { get; set; }
		public string EarLeft_Z { get; set; }
		public string EarLeft_W { get; set; }
		public string EarRight_X { get; set; }
		public string EarRight_Y { get; set; }
		public string EarRight_Z { get; set; }
		public string EarRight_W { get; set; }
		public string ForearmLeft_X { get; set; }
		public string ForearmLeft_Y { get; set; }
		public string ForearmLeft_Z { get; set; }
		public string ForearmLeft_W { get; set; }
		public string ForearmRight_X { get; set; }
		public string ForearmRight_Y { get; set; }
		public string ForearmRight_Z { get; set; }
		public string ForearmRight_W { get; set; }
		public string ShoulderLeft_X { get; set; }
		public string ShoulderLeft_Y { get; set; }
		public string ShoulderLeft_Z { get; set; }
		public string ShoulderLeft_W { get; set; }
		public string ShoulderRight_X { get; set; }
		public string ShoulderRight_Y { get; set; }
		public string ShoulderRight_Z { get; set; }
		public string ShoulderRight_W { get; set; }
		public string HairB_X { get; set; }
		public string HairB_Y { get; set; }
		public string HairB_Z { get; set; }
		public string HairB_W { get; set; }
		public string HandLeft_X { get; set; }
		public string HandLeft_Y { get; set; }
		public string HandLeft_Z { get; set; }
		public string HandLeft_W { get; set; }
		public string HandRight_X { get; set; }
		public string HandRight_Y { get; set; }
		public string HandRight_Z { get; set; }
		public string HandRight_W { get; set; }
		public string ShieldLeft_X { get; set; }
		public string ShieldLeft_Y { get; set; }
		public string ShieldLeft_Z { get; set; }
		public string ShieldLeft_W { get; set; }
		public string ShieldRight_X { get; set; }
		public string ShieldRight_Y { get; set; }
		public string ShieldRight_Z { get; set; }
		public string ShieldRight_W { get; set; }
		public string EarringALeft_X { get; set; }
		public string EarringALeft_Y { get; set; }
		public string EarringALeft_Z { get; set; }
		public string EarringALeft_W { get; set; }
		public string EarringARight_X { get; set; }
		public string EarringARight_Y { get; set; }
		public string EarringARight_Z { get; set; }
		public string EarringARight_W { get; set; }
		public string ElbowLeft_X { get; set; }
		public string ElbowLeft_Y { get; set; }
		public string ElbowLeft_Z { get; set; }
		public string ElbowLeft_W { get; set; }
		public string ElbowRight_X { get; set; }
		public string ElbowRight_Y { get; set; }
		public string ElbowRight_Z { get; set; }
		public string ElbowRight_W { get; set; }
		public string CouterLeft_X { get; set; }
		public string CouterLeft_Y { get; set; }
		public string CouterLeft_Z { get; set; }
		public string CouterLeft_W { get; set; }
		public string CouterRight_X { get; set; }
		public string CouterRight_Y { get; set; }
		public string CouterRight_Z { get; set; }
		public string CouterRight_W { get; set; }
		public string WristLeft_X { get; set; }
		public string WristLeft_Y { get; set; }
		public string WristLeft_Z { get; set; }
		public string WristLeft_W { get; set; }
		public string WristRight_X { get; set; }
		public string WristRight_Y { get; set; }
		public string WristRight_Z { get; set; }
		public string WristRight_W { get; set; }
		public string IndexALeft_X { get; set; }
		public string IndexALeft_Y { get; set; }
		public string IndexALeft_Z { get; set; }
		public string IndexALeft_W { get; set; }
		public string IndexARight_X { get; set; }
		public string IndexARight_Y { get; set; }
		public string IndexARight_Z { get; set; }
		public string IndexARight_W { get; set; }
		public string PinkyALeft_X { get; set; }
		public string PinkyALeft_Y { get; set; }
		public string PinkyALeft_Z { get; set; }
		public string PinkyALeft_W { get; set; }
		public string PinkyARight_X { get; set; }
		public string PinkyARight_Y { get; set; }
		public string PinkyARight_Z { get; set; }
		public string PinkyARight_W { get; set; }
		public string RingALeft_X { get; set; }
		public string RingALeft_Y { get; set; }
		public string RingALeft_Z { get; set; }
		public string RingALeft_W { get; set; }
		public string RingARight_X { get; set; }
		public string RingARight_Y { get; set; }
		public string RingARight_Z { get; set; }
		public string RingARight_W { get; set; }
		public string MiddleALeft_X { get; set; }
		public string MiddleALeft_Y { get; set; }
		public string MiddleALeft_Z { get; set; }
		public string MiddleALeft_W { get; set; }
		public string MiddleARight_X { get; set; }
		public string MiddleARight_Y { get; set; }
		public string MiddleARight_Z { get; set; }
		public string MiddleARight_W { get; set; }
		public string ThumbALeft_X { get; set; }
		public string ThumbALeft_Y { get; set; }
		public string ThumbALeft_Z { get; set; }
		public string ThumbALeft_W { get; set; }
		public string ThumbARight_X { get; set; }
		public string ThumbARight_Y { get; set; }
		public string ThumbARight_Z { get; set; }
		public string ThumbARight_W { get; set; }
		public string WeaponLeft_X { get; set; }
		public string WeaponLeft_Y { get; set; }
		public string WeaponLeft_Z { get; set; }
		public string WeaponLeft_W { get; set; }
		public string WeaponRight_X { get; set; }
		public string WeaponRight_Y { get; set; }
		public string WeaponRight_Z { get; set; }
		public string WeaponRight_W { get; set; }
		public string EarringBLeft_X { get; set; }
		public string EarringBLeft_Y { get; set; }
		public string EarringBLeft_Z { get; set; }
		public string EarringBLeft_W { get; set; }
		public string EarringBRight_X { get; set; }
		public string EarringBRight_Y { get; set; }
		public string EarringBRight_Z { get; set; }
		public string EarringBRight_W { get; set; }
		public string IndexBLeft_X { get; set; }
		public string IndexBLeft_Y { get; set; }
		public string IndexBLeft_Z { get; set; }
		public string IndexBLeft_W { get; set; }
		public string IndexBRight_X { get; set; }
		public string IndexBRight_Y { get; set; }
		public string IndexBRight_Z { get; set; }
		public string IndexBRight_W { get; set; }
		public string PinkyBLeft_X { get; set; }
		public string PinkyBLeft_Y { get; set; }
		public string PinkyBLeft_Z { get; set; }
		public string PinkyBLeft_W { get; set; }
		public string PinkyBRight_X { get; set; }
		public string PinkyBRight_Y { get; set; }
		public string PinkyBRight_Z { get; set; }
		public string PinkyBRight_W { get; set; }
		public string RingBLeft_X { get; set; }
		public string RingBLeft_Y { get; set; }
		public string RingBLeft_Z { get; set; }
		public string RingBLeft_W { get; set; }
		public string RingBRight_X { get; set; }
		public string RingBRight_Y { get; set; }
		public string RingBRight_Z { get; set; }
		public string RingBRight_W { get; set; }
		public string MiddleBLeft_X { get; set; }
		public string MiddleBLeft_Y { get; set; }
		public string MiddleBLeft_Z { get; set; }
		public string MiddleBLeft_W { get; set; }
		public string MiddleBRight_X { get; set; }
		public string MiddleBRight_Y { get; set; }
		public string MiddleBRight_Z { get; set; }
		public string MiddleBRight_W { get; set; }
		public string ThumbBLeft_X { get; set; }
		public string ThumbBLeft_Y { get; set; }
		public string ThumbBLeft_Z { get; set; }
		public string ThumbBLeft_W { get; set; }
		public string ThumbBRight_X { get; set; }
		public string ThumbBRight_Y { get; set; }
		public string ThumbBRight_Z { get; set; }
		public string ThumbBRight_W { get; set; }
		public string TailA_X { get; set; }
		public string TailA_Y { get; set; }
		public string TailA_Z { get; set; }
		public string TailA_W { get; set; }
		public string TailB_X { get; set; }
		public string TailB_Y { get; set; }
		public string TailB_Z { get; set; }
		public string TailB_W { get; set; }
		public string TailC_X { get; set; }
		public string TailC_Y { get; set; }
		public string TailC_Z { get; set; }
		public string TailC_W { get; set; }
		public string TailD_X { get; set; }
		public string TailD_Y { get; set; }
		public string TailD_Z { get; set; }
		public string TailD_W { get; set; }
		public string TailE_X { get; set; }
		public string TailE_Y { get; set; }
		public string TailE_Z { get; set; }
		public string TailE_W { get; set; }
		public string RootHead_X { get; set; }
		public string RootHead_Y { get; set; }
		public string RootHead_Z { get; set; }
		public string RootHead_W { get; set; }
		public string Jaw_X { get; set; }
		public string Jaw_Y { get; set; }
		public string Jaw_Z { get; set; }
		public string Jaw_W { get; set; }
		public string EyelidLowerLeft_X { get; set; }
		public string EyelidLowerLeft_Y { get; set; }
		public string EyelidLowerLeft_Z { get; set; }
		public string EyelidLowerLeft_W { get; set; }
		public string EyelidLowerRight_X { get; set; }
		public string EyelidLowerRight_Y { get; set; }
		public string EyelidLowerRight_Z { get; set; }
		public string EyelidLowerRight_W { get; set; }
		public string EyeLeft_X { get; set; }
		public string EyeLeft_Y { get; set; }
		public string EyeLeft_Z { get; set; }
		public string EyeLeft_W { get; set; }
		public string EyeRight_X { get; set; }
		public string EyeRight_Y { get; set; }
		public string EyeRight_Z { get; set; }
		public string EyeRight_W { get; set; }
		public string Nose_X { get; set; }
		public string Nose_Y { get; set; }
		public string Nose_Z { get; set; }
		public string Nose_W { get; set; }
		public string CheekLeft_X { get; set; }
		public string CheekLeft_Y { get; set; }
		public string CheekLeft_Z { get; set; }
		public string CheekLeft_W { get; set; }
		public string HrothWhiskersLeft_X { get; set; }
		public string HrothWhiskersLeft_Y { get; set; }
		public string HrothWhiskersLeft_Z { get; set; }
		public string HrothWhiskersLeft_W { get; set; }
		public string CheekRight_X { get; set; }
		public string CheekRight_Y { get; set; }
		public string CheekRight_Z { get; set; }
		public string CheekRight_W { get; set; }
		public string HrothWhiskersRight_X { get; set; }
		public string HrothWhiskersRight_Y { get; set; }
		public string HrothWhiskersRight_Z { get; set; }
		public string HrothWhiskersRight_W { get; set; }
		public string LipsLeft_X { get; set; }
		public string LipsLeft_Y { get; set; }
		public string LipsLeft_Z { get; set; }
		public string LipsLeft_W { get; set; }
		public string HrothEyebrowLeft_X { get; set; }
		public string HrothEyebrowLeft_Y { get; set; }
		public string HrothEyebrowLeft_Z { get; set; }
		public string HrothEyebrowLeft_W { get; set; }
		public string LipsRight_X { get; set; }
		public string LipsRight_Y { get; set; }
		public string LipsRight_Z { get; set; }
		public string LipsRight_W { get; set; }
		public string HrothEyebrowRight_X { get; set; }
		public string HrothEyebrowRight_Y { get; set; }
		public string HrothEyebrowRight_Z { get; set; }
		public string HrothEyebrowRight_W { get; set; }
		public string EyebrowLeft_X { get; set; }
		public string EyebrowLeft_Y { get; set; }
		public string EyebrowLeft_Z { get; set; }
		public string EyebrowLeft_W { get; set; }
		public string HrothBridge_X { get; set; }
		public string HrothBridge_Y { get; set; }
		public string HrothBridge_Z { get; set; }
		public string HrothBridge_W { get; set; }
		public string EyebrowRight_X { get; set; }
		public string EyebrowRight_Y { get; set; }
		public string EyebrowRight_Z { get; set; }
		public string EyebrowRight_W { get; set; }
		public string HrothBrowLeft_X { get; set; }
		public string HrothBrowLeft_Y { get; set; }
		public string HrothBrowLeft_Z { get; set; }
		public string HrothBrowLeft_W { get; set; }
		public string Bridge_X { get; set; }
		public string Bridge_Y { get; set; }
		public string Bridge_Z { get; set; }
		public string Bridge_W { get; set; }
		public string HrothBrowRight_X { get; set; }
		public string HrothBrowRight_Y { get; set; }
		public string HrothBrowRight_Z { get; set; }
		public string HrothBrowRight_W { get; set; }
		public string BrowLeft_X { get; set; }
		public string BrowLeft_Y { get; set; }
		public string BrowLeft_Z { get; set; }
		public string BrowLeft_W { get; set; }
		public string HrothJawUpper_X { get; set; }
		public string HrothJawUpper_Y { get; set; }
		public string HrothJawUpper_Z { get; set; }
		public string HrothJawUpper_W { get; set; }
		public string BrowRight_X { get; set; }
		public string BrowRight_Y { get; set; }
		public string BrowRight_Z { get; set; }
		public string BrowRight_W { get; set; }
		public string HrothLipUpper_X { get; set; }
		public string HrothLipUpper_Y { get; set; }
		public string HrothLipUpper_Z { get; set; }
		public string HrothLipUpper_W { get; set; }
		public string LipUpperA_X { get; set; }
		public string LipUpperA_Y { get; set; }
		public string LipUpperA_Z { get; set; }
		public string LipUpperA_W { get; set; }
		public string HrothEyelidUpperLeft_X { get; set; }
		public string HrothEyelidUpperLeft_Y { get; set; }
		public string HrothEyelidUpperLeft_Z { get; set; }
		public string HrothEyelidUpperLeft_W { get; set; }
		public string EyelidUpperLeft_X { get; set; }
		public string EyelidUpperLeft_Y { get; set; }
		public string EyelidUpperLeft_Z { get; set; }
		public string EyelidUpperLeft_W { get; set; }
		public string HrothEyelidUpperRight_X { get; set; }
		public string HrothEyelidUpperRight_Y { get; set; }
		public string HrothEyelidUpperRight_Z { get; set; }
		public string HrothEyelidUpperRight_W { get; set; }
		public string EyelidUpperRight_X { get; set; }
		public string EyelidUpperRight_Y { get; set; }
		public string EyelidUpperRight_Z { get; set; }
		public string EyelidUpperRight_W { get; set; }
		public string HrothLipsLeft_X { get; set; }
		public string HrothLipsLeft_Y { get; set; }
		public string HrothLipsLeft_Z { get; set; }
		public string HrothLipsLeft_W { get; set; }
		public string LipLowerA_X { get; set; }
		public string LipLowerA_Y { get; set; }
		public string LipLowerA_Z { get; set; }
		public string LipLowerA_W { get; set; }
		public string HrothLipsRight_X { get; set; }
		public string HrothLipsRight_Y { get; set; }
		public string HrothLipsRight_Z { get; set; }
		public string HrothLipsRight_W { get; set; }
		public string VieraEar01ALeft_X { get; set; }
		public string VieraEar01ALeft_Y { get; set; }
		public string VieraEar01ALeft_Z { get; set; }
		public string VieraEar01ALeft_W { get; set; }
		public string LipUpperB_X { get; set; }
		public string LipUpperB_Y { get; set; }
		public string LipUpperB_Z { get; set; }
		public string LipUpperB_W { get; set; }
		public string HrothLipUpperLeft_X { get; set; }
		public string HrothLipUpperLeft_Y { get; set; }
		public string HrothLipUpperLeft_Z { get; set; }
		public string HrothLipUpperLeft_W { get; set; }
		public string VieraEar01ARight_X { get; set; }
		public string VieraEar01ARight_Y { get; set; }
		public string VieraEar01ARight_Z { get; set; }
		public string VieraEar01ARight_W { get; set; }
		public string LipLowerB_X { get; set; }
		public string LipLowerB_Y { get; set; }
		public string LipLowerB_Z { get; set; }
		public string LipLowerB_W { get; set; }
		public string HrothLipUpperRight_X { get; set; }
		public string HrothLipUpperRight_Y { get; set; }
		public string HrothLipUpperRight_Z { get; set; }
		public string HrothLipUpperRight_W { get; set; }
		public string VieraEar02ALeft_X { get; set; }
		public string VieraEar02ALeft_Y { get; set; }
		public string VieraEar02ALeft_Z { get; set; }
		public string VieraEar02ALeft_W { get; set; }
		public string HrothLipLower_X { get; set; }
		public string HrothLipLower_Y { get; set; }
		public string HrothLipLower_Z { get; set; }
		public string HrothLipLower_W { get; set; }
		public string VieraEar02ARight_X { get; set; }
		public string VieraEar02ARight_Y { get; set; }
		public string VieraEar02ARight_Z { get; set; }
		public string VieraEar02ARight_W { get; set; }
		public string VieraEar03ALeft_X { get; set; }
		public string VieraEar03ALeft_Y { get; set; }
		public string VieraEar03ALeft_Z { get; set; }
		public string VieraEar03ALeft_W { get; set; }
		public string VieraEar03ARight_X { get; set; }
		public string VieraEar03ARight_Y { get; set; }
		public string VieraEar03ARight_Z { get; set; }
		public string VieraEar03ARight_W { get; set; }
		public string VieraEar04ALeft_X { get; set; }
		public string VieraEar04ALeft_Y { get; set; }
		public string VieraEar04ALeft_Z { get; set; }
		public string VieraEar04ALeft_W { get; set; }
		public string VieraEar04ARight_X { get; set; }
		public string VieraEar04ARight_Y { get; set; }
		public string VieraEar04ARight_Z { get; set; }
		public string VieraEar04ARight_W { get; set; }
		public string VieraLipLowerA_X { get; set; }
		public string VieraLipLowerA_Y { get; set; }
		public string VieraLipLowerA_Z { get; set; }
		public string VieraLipLowerA_W { get; set; }
		public string VieraLipUpperB_X { get; set; }
		public string VieraLipUpperB_Y { get; set; }
		public string VieraLipUpperB_Z { get; set; }
		public string VieraLipUpperB_W { get; set; }
		public string VieraEar01BLeft_X { get; set; }
		public string VieraEar01BLeft_Y { get; set; }
		public string VieraEar01BLeft_Z { get; set; }
		public string VieraEar01BLeft_W { get; set; }
		public string VieraEar01BRight_X { get; set; }
		public string VieraEar01BRight_Y { get; set; }
		public string VieraEar01BRight_Z { get; set; }
		public string VieraEar01BRight_W { get; set; }
		public string VieraEar02BLeft_X { get; set; }
		public string VieraEar02BLeft_Y { get; set; }
		public string VieraEar02BLeft_Z { get; set; }
		public string VieraEar02BLeft_W { get; set; }
		public string VieraEar02BRight_X { get; set; }
		public string VieraEar02BRight_Y { get; set; }
		public string VieraEar02BRight_Z { get; set; }
		public string VieraEar02BRight_W { get; set; }
		public string VieraEar03BLeft_X { get; set; }
		public string VieraEar03BLeft_Y { get; set; }
		public string VieraEar03BLeft_Z { get; set; }
		public string VieraEar03BLeft_W { get; set; }
		public string VieraEar03BRight_X { get; set; }
		public string VieraEar03BRight_Y { get; set; }
		public string VieraEar03BRight_Z { get; set; }
		public string VieraEar03BRight_W { get; set; }
		public string VieraEar04BLeft_X { get; set; }
		public string VieraEar04BLeft_Y { get; set; }
		public string VieraEar04BLeft_Z { get; set; }
		public string VieraEar04BLeft_W { get; set; }
		public string VieraEar04BRight_X { get; set; }
		public string VieraEar04BRight_Y { get; set; }
		public string VieraEar04BRight_Z { get; set; }
		public string VieraEar04BRight_W { get; set; }
		public string VieraLipLowerB_X { get; set; }
		public string VieraLipLowerB_Y { get; set; }
		public string VieraLipLowerB_Z { get; set; }
		public string VieraLipLowerB_W { get; set; }
		public string ExHair_Value { get; set; }
		public string ExRootHair_X { get; set; }
		public string ExRootHair_Y { get; set; }
		public string ExRootHair_Z { get; set; }
		public string ExRootHair_W { get; set; }
		public string ExHairA_X { get; set; }
		public string ExHairA_Y { get; set; }
		public string ExHairA_Z { get; set; }
		public string ExHairA_W { get; set; }
		public string ExHairB_X { get; set; }
		public string ExHairB_Y { get; set; }
		public string ExHairB_Z { get; set; }
		public string ExHairB_W { get; set; }
		public string ExHairC_X { get; set; }
		public string ExHairC_Y { get; set; }
		public string ExHairC_Z { get; set; }
		public string ExHairC_W { get; set; }
		public string ExHairD_X { get; set; }
		public string ExHairD_Y { get; set; }
		public string ExHairD_Z { get; set; }
		public string ExHairD_W { get; set; }
		public string ExHairE_X { get; set; }
		public string ExHairE_Y { get; set; }
		public string ExHairE_Z { get; set; }
		public string ExHairE_W { get; set; }
		public string ExHairF_X { get; set; }
		public string ExHairF_Y { get; set; }
		public string ExHairF_Z { get; set; }
		public string ExHairF_W { get; set; }
		public string ExHairG_X { get; set; }
		public string ExHairG_Y { get; set; }
		public string ExHairG_Z { get; set; }
		public string ExHairG_W { get; set; }
		public string ExHairH_X { get; set; }
		public string ExHairH_Y { get; set; }
		public string ExHairH_Z { get; set; }
		public string ExHairH_W { get; set; }
		public string ExHairI_X { get; set; }
		public string ExHairI_Y { get; set; }
		public string ExHairI_Z { get; set; }
		public string ExHairI_W { get; set; }
		public string ExHairJ_X { get; set; }
		public string ExHairJ_Y { get; set; }
		public string ExHairJ_Z { get; set; }
		public string ExHairJ_W { get; set; }
		public string ExHairK_X { get; set; }
		public string ExHairK_Y { get; set; }
		public string ExHairK_Z { get; set; }
		public string ExHairK_W { get; set; }
		public string ExHairL_X { get; set; }
		public string ExHairL_Y { get; set; }
		public string ExHairL_Z { get; set; }
		public string ExHairL_W { get; set; }
		public string ExMet_Value { get; set; }
		public string ExRootMet_X { get; set; }
		public string ExRootMet_Y { get; set; }
		public string ExRootMet_Z { get; set; }
		public string ExRootMet_W { get; set; }
		public string ExMetA_X { get; set; }
		public string ExMetA_Y { get; set; }
		public string ExMetA_Z { get; set; }
		public string ExMetA_W { get; set; }
		public string ExMetB_X { get; set; }
		public string ExMetB_Y { get; set; }
		public string ExMetB_Z { get; set; }
		public string ExMetB_W { get; set; }
		public string ExMetC_X { get; set; }
		public string ExMetC_Y { get; set; }
		public string ExMetC_Z { get; set; }
		public string ExMetC_W { get; set; }
		public string ExMetD_X { get; set; }
		public string ExMetD_Y { get; set; }
		public string ExMetD_Z { get; set; }
		public string ExMetD_W { get; set; }
		public string ExMetE_X { get; set; }
		public string ExMetE_Y { get; set; }
		public string ExMetE_Z { get; set; }
		public string ExMetE_W { get; set; }
		public string ExMetF_X { get; set; }
		public string ExMetF_Y { get; set; }
		public string ExMetF_Z { get; set; }
		public string ExMetF_W { get; set; }
		public string ExMetG_X { get; set; }
		public string ExMetG_Y { get; set; }
		public string ExMetG_Z { get; set; }
		public string ExMetG_W { get; set; }
		public string ExMetH_X { get; set; }
		public string ExMetH_Y { get; set; }
		public string ExMetH_Z { get; set; }
		public string ExMetH_W { get; set; }
		public string ExMetI_X { get; set; }
		public string ExMetI_Y { get; set; }
		public string ExMetI_Z { get; set; }
		public string ExMetI_W { get; set; }
		public string ExMetJ_X { get; set; }
		public string ExMetJ_Y { get; set; }
		public string ExMetJ_Z { get; set; }
		public string ExMetJ_W { get; set; }
		public string ExMetK_X { get; set; }
		public string ExMetK_Y { get; set; }
		public string ExMetK_Z { get; set; }
		public string ExMetK_W { get; set; }
		public string ExMetL_X { get; set; }
		public string ExMetL_Y { get; set; }
		public string ExMetL_Z { get; set; }
		public string ExMetL_W { get; set; }
		public string ExMetM_X { get; set; }
		public string ExMetM_Y { get; set; }
		public string ExMetM_Z { get; set; }
		public string ExMetM_W { get; set; }
		public string ExMetN_X { get; set; }
		public string ExMetN_Y { get; set; }
		public string ExMetN_Z { get; set; }
		public string ExMetN_W { get; set; }
		public string ExMetO_X { get; set; }
		public string ExMetO_Y { get; set; }
		public string ExMetO_Z { get; set; }
		public string ExMetO_W { get; set; }
		public string ExMetP_X { get; set; }
		public string ExMetP_Y { get; set; }
		public string ExMetP_Z { get; set; }
		public string ExMetP_W { get; set; }
		public string ExMetQ_X { get; set; }
		public string ExMetQ_Y { get; set; }
		public string ExMetQ_Z { get; set; }
		public string ExMetQ_W { get; set; }
		public string ExMetR_X { get; set; }
		public string ExMetR_Y { get; set; }
		public string ExMetR_Z { get; set; }
		public string ExMetR_W { get; set; }
		public string ExTop_Value { get; set; }
		public string ExRootTop_X { get; set; }
		public string ExRootTop_Y { get; set; }
		public string ExRootTop_Z { get; set; }
		public string ExRootTop_W { get; set; }
		public string ExTopA_X { get; set; }
		public string ExTopA_Y { get; set; }
		public string ExTopA_Z { get; set; }
		public string ExTopA_W { get; set; }
		public string ExTopB_X { get; set; }
		public string ExTopB_Y { get; set; }
		public string ExTopB_Z { get; set; }
		public string ExTopB_W { get; set; }
		public string ExTopC_X { get; set; }
		public string ExTopC_Y { get; set; }
		public string ExTopC_Z { get; set; }
		public string ExTopC_W { get; set; }
		public string ExTopD_X { get; set; }
		public string ExTopD_Y { get; set; }
		public string ExTopD_Z { get; set; }
		public string ExTopD_W { get; set; }
		public string ExTopE_X { get; set; }
		public string ExTopE_Y { get; set; }
		public string ExTopE_Z { get; set; }
		public string ExTopE_W { get; set; }
		public string ExTopF_X { get; set; }
		public string ExTopF_Y { get; set; }
		public string ExTopF_Z { get; set; }
		public string ExTopF_W { get; set; }
		public string ExTopG_X { get; set; }
		public string ExTopG_Y { get; set; }
		public string ExTopG_Z { get; set; }
		public string ExTopG_W { get; set; }
		public string ExTopH_X { get; set; }
		public string ExTopH_Y { get; set; }
		public string ExTopH_Z { get; set; }
		public string ExTopH_W { get; set; }
		public string ExTopI_X { get; set; }
		public string ExTopI_Y { get; set; }
		public string ExTopI_Z { get; set; }
		public string ExTopI_W { get; set; }
	}
}
